on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish (w/o rendering)

defaults:
  run:
    working-directory: 2022

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          render: false
          path: 2022
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}